# ext/bbdkp/bbguild/config/routing.yml
bbdkp_bbguild_00:
    path: /guild/{page}/{guild_id}
    defaults: { _controller: bbdkp.bbguild.controller:handleguild , guild_id: 1, page: welcome }
    requirements:
        guild_id: \d*
        page: welcome|roster|achievements
bbdkp_bbguild_01:
    path: /getfaction/{game_id}
    defaults: { _controller:bbdkp.bbguild.admin.controller:getFaction, game_id: wow}